// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Petshelter edit', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Petshelter edit', async function() {
    // Test name: Petshelter edit
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 579x748 | 
    await driver.manage().window().setRect({ width: 579, height: 748 })
    // 3 | click | linkText=Edit | 
    await driver.findElement(By.linkText("Edit")).click()
    // 4 | click | name=name | 
    await driver.findElement(By.name("name")).click()
    // 5 | type | name=name | Clay 
    await driver.findElement(By.name("name")).sendKeys("Clay ")
    // 6 | click | name=description | 
    await driver.findElement(By.name("description")).click()
    // 7 | click | name=description | 
    await driver.findElement(By.name("description")).click()
    // 8 | type | name=description | pure white
    await driver.findElement(By.name("description")).sendKeys("pure white")
    // 9 | click | name=skills[0] | 
    await driver.findElement(By.name("skills[0]")).click()
    // 10 | type | name=skills[0] | eat now
    await driver.findElement(By.name("skills[0]")).sendKeys("eat now")
    // 11 | click | name=skills[1] | 
    await driver.findElement(By.name("skills[1]")).click()
    // 12 | type | name=skills[1] | sleep later
    await driver.findElement(By.name("skills[1]")).sendKeys("sleep later")
    // 13 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
  })
})
