// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Petshelter add', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Petshelter add', async function() {
    // Test name: Petshelter add
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 579x748 | 
    await driver.manage().window().setRect({ width: 579, height: 748 })
    // 3 | click | linkText=Add pet to Shelter | 
    await driver.findElement(By.linkText("Add pet to Shelter")).click()
    // 4 | click | name=name | 
    await driver.findElement(By.name("name")).click()
    // 5 | type | name=name | Clay
    await driver.findElement(By.name("name")).sendKeys("Clay")
    // 6 | click | name=description | 
    await driver.findElement(By.name("description")).click()
    // 7 | type | name=description | white
    await driver.findElement(By.name("description")).sendKeys("white")
    // 8 | click | name=skills[0] | 
    await driver.findElement(By.name("skills[0]")).click()
    // 9 | type | name=skills[0] | eat
    await driver.findElement(By.name("skills[0]")).sendKeys("eat")
    // 10 | type | name=skills[1] | sleep
    await driver.findElement(By.name("skills[1]")).sendKeys("sleep")
    // 11 | type | name=skills[2] | bark
    await driver.findElement(By.name("skills[2]")).sendKeys("bark")
    // 12 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
  })
})
