// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Petshelter adopt', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Petshelter adopt', async function() {
    // Test name: Petshelter adopt
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/ | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 579x748 | 
    await driver.manage().window().setRect({ width: 579, height: 748 })
    // 3 | click | css=tr:nth-child(1) .show_pet_details_btn | 
    await driver.findElement(By.css("tr:nth-child(1) .show_pet_details_btn")).click()
    // 4 | click | id=adopt_pet_btn | 
    await driver.findElement(By.id("adopt_pet_btn")).click()
  })
})
